id: IE59A7AE5
legacy_id: P003024
ocr_import_info:
  bdrc_scan_id: W27872
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T08:18:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:33:50.381067+00:00'
last_modified: 2022-09-02 15:34:27.116062
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27872
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27872
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཁའ་འགྲོ་བདུད་འདུལ་དྲག་མོའི་ཆོས་སྐོར་གཏེར་གཞུང་།
  author: ནུས་ལྡན་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.649750143671492
  ocr_word_median_confidence_index: 0.6899999976158142
quality: null
bases:
  I4491:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4491
      total_pages: 733
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4491.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.649750143671492
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
