id: P003024
initial_creation_type: ocr
source_metadata:
  id: bdr:W27872
  title: མཁའ་འགྲོ་བདུད་འདུལ་དྲག་མོའི་ཆོས་སྐོར་གཏེར་གཞུང
  author: ''
  volumes:
    a9a8917ea9f045dda184afb8f2138975:
      image_group_id: I4491
      title: ''
      volume_number: 1
      total_pages: 733
